const state={materials:[],categories:[],page:1,pageSize:12,query:'',category:'',type:'',grade:''};
const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const demoCategories=[{id:'demo-kimia',name:'Kimia',icon:'⚗',description:'Materi pembelajaran kimia'},{id:'demo-media',name:'Media Interaktif',icon:'◈',description:'Media digital dan simulasi'},{id:'demo-tka',name:'TKA',icon:'✦',description:'Latihan dan asesmen'}];
const demoMaterials=[{id:'d1',title:'Redoks Interaktif',description:'Media interaktif untuk mempelajari penyetaraan reaksi redoks.',category_id:'demo-kimia',subject:'Kimia',grade:'XII',material_type:'Media Pembelajaran',tags:['redoks','interaktif'],featured:true,published:true,resource_url:'#'},{id:'d2',title:'Mistery Card Konfigurasi Elektron',description:'Eksplorasi konfigurasi elektron dan posisi unsur dalam tabel periodik.',category_id:'demo-media',subject:'Kimia',grade:'X',material_type:'Game Edukasi',tags:['konfigurasi elektron','periodik'],featured:true,published:true,resource_url:'#'},{id:'d3',title:'TKA Kimia XII',description:'Latihan soal berbasis kompetensi dan penalaran.',category_id:'demo-tka',subject:'Kimia',grade:'XII',material_type:'TKA',tags:['tka','hots'],featured:false,published:true,resource_url:'#'}];
function toast(m){const e=$('#toast');e.textContent=m;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2600)}
function theme(){const dark=localStorage.getItem('wp-theme')==='dark';document.documentElement.classList.toggle('dark',dark);const b=$('#themeBtn');if(b)b.textContent=dark?'☀':'☾'}
function materialCard(m){const c=state.categories.find(x=>x.id===m.category_id);const tags=Array.isArray(m.tags)?m.tags:(m.tags||'').split(',').map(x=>x.trim()).filter(Boolean);const href=m.resource_url||m.external_url||'#';return `<article class="material-card"><div class="thumb" ${m.thumbnail_url?`style="background-image:url('${esc(m.thumbnail_url)}')"`:''}><span class="type-badge">${esc(m.material_type||'Resource')}</span>${m.featured?'<span class="featured-badge">★</span>':''}<div class="thumb-fallback">${m.thumbnail_url?'':'✦'}</div></div><div class="card-body"><div class="meta"><span>${esc(c?.name||m.subject||'Resource')}</span><span>${esc(m.grade||'')}</span></div><h3>${esc(m.title)}</h3><p>${esc(m.description||'')}</p><div class="tags">${tags.slice(0,3).map(t=>`<span>#${esc(t)}</span>`).join('')}</div><a class="open-link" href="${esc(href)}" ${href!=='#'?'target="_blank" rel="noopener"':''} data-recent="${esc(m.id)}">Buka materi <span>↗</span></a></div></article>`}
async function load(){if(!sbConfigured){state.categories=demoCategories;state.materials=demoMaterials;fillFilters();$('#resultCount').textContent='Mode demo — konfigurasi Supabase untuk data online';render();return} try{const s=requireSupabase();const [{data:c,error:ce},{data:m,error:me}]=await Promise.all([s.from('categories').select('*').order('sort_order').order('name'),s.from('materials').select('*').eq('is_published',true).order('created_at',{ascending:false})]);if(ce)throw ce;if(me)throw me;state.categories=c||[];state.materials=m||[];fillFilters();render()}catch(e){console.error(e);toast('Data belum dapat dimuat. Periksa konfigurasi Supabase.');state.categories=demoCategories;state.materials=demoMaterials;fillFilters();render()}}
function filtered(){const q=state.query.toLowerCase();return state.materials.filter(m=>{const hay=[m.title,m.description,m.subject,m.grade,m.material_type,Array.isArray(m.tags)?m.tags.join(' '):m.tags].join(' ').toLowerCase();return(!q||hay.includes(q))&&(!state.category||m.category_id===state.category)&&(!state.type||m.material_type===state.type)&&(!state.grade||m.grade===state.grade)})}
function fillFilters(){const cf=$('#categoryFilter'),tf=$('#typeFilter'),gf=$('#gradeFilter');cf.innerHTML='<option value="">Semua kategori</option>';tf.innerHTML='<option value="">Semua jenis</option>';gf.innerHTML='<option value="">Semua kelas</option>';state.categories.forEach(c=>cf.insertAdjacentHTML('beforeend',`<option value="${esc(c.id)}">${esc(c.name)}</option>`));[...new Set(state.materials.map(m=>m.material_type).filter(Boolean))].sort().forEach(v=>tf.insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`));[...new Set(state.materials.map(m=>m.grade).filter(Boolean))].sort().forEach(v=>gf.insertAdjacentHTML('beforeend',`<option>${esc(v)}</option>`))}
function render(){const list=filtered();const pages=Math.max(1,Math.ceil(list.length/state.pageSize));if(state.page>pages)state.page=pages;const start=(state.page-1)*state.pageSize;const pageItems=list.slice(start,start+state.pageSize);$('#resultCount').textContent=`${list.length} materi`;$('#materialsGrid').innerHTML=pageItems.map(materialCard).join('');const featured=state.materials.filter(m=>m.featured).slice(0,4);$('#featuredGrid').innerHTML=featured.map(materialCard).join('');$('#featuredWrap').classList.toggle('hidden',!featured.length);$('#emptyState').classList.toggle('hidden',!!pageItems.length);$('#pagination').innerHTML=pages>1?Array.from({length:pages},(_,i)=>`<button class="page-btn ${i+1===state.page?'active':''}" data-page="${i+1}">${i+1}</button>`).join(''):'';$('#categoryGrid').innerHTML=state.categories.map(c=>{const count=state.materials.filter(m=>m.category_id===c.id).length;return `<button class="category-card" data-category="${esc(c.id)}"><span>${esc(c.icon||'✦')}</span><b>${esc(c.name)}</b><small>${count} materi</small></button>`}).join('');$('#statMaterials').textContent=state.materials.length+'+';$('#statCategories').textContent=state.categories.length;$('#statInteractive').textContent=state.materials.filter(m=>/interaktif|game|simulasi/i.test(m.material_type||'')).length;$('#statClasses').textContent=new Set(state.materials.map(m=>m.grade).filter(Boolean)).size;renderRecent()}
function renderRecent(){const ids=JSON.parse(localStorage.getItem('wp-recent')||'[]');const recent=ids.map(id=>state.materials.find(m=>String(m.id)===String(id))).filter(Boolean).slice(0,4);$('#recentSection').classList.toggle('hidden',!recent.length);$('#recentGrid').innerHTML=recent.map(materialCard).join('')}
function remember(id){let ids=JSON.parse(localStorage.getItem('wp-recent')||'[]').filter(x=>String(x)!==String(id));ids.unshift(id);localStorage.setItem('wp-recent',JSON.stringify(ids.slice(0,8)))}
function events(){['searchInput'].forEach(id=>$('#'+id).addEventListener('input',e=>{state.query=e.target.value;state.page=1;render()}));[['categoryFilter','category'],['typeFilter','type'],['gradeFilter','grade']].forEach(([id,key])=>$('#'+id).addEventListener('change',e=>{state[key]=e.target.value;state.page=1;render()}));$('#resetBtn').onclick=()=>{state.query=state.category=state.type=state.grade='';$('#searchInput').value='';$('#categoryFilter').value=$('#typeFilter').value=$('#gradeFilter').value='';render()};document.addEventListener('click',e=>{const p=e.target.closest('[data-page]');if(p){state.page=+p.dataset.page;render();window.scrollTo({top:document.querySelector('#library').offsetTop-70,behavior:'smooth'})}const cat=e.target.closest('[data-category]');if(cat){state.category=cat.dataset.category;$('#categoryFilter').value=state.category;state.page=1;document.querySelector('#library').scrollIntoView({behavior:'smooth'});render()}const rec=e.target.closest('[data-recent]');if(rec)remember(rec.dataset.recent)});$('#clearRecent').onclick=()=>{localStorage.removeItem('wp-recent');render()};$('#themeBtn').onclick=()=>{localStorage.setItem('wp-theme',localStorage.getItem('wp-theme')==='dark'?'light':'dark');theme()}}
theme();fillFilters();events();load();
